# Generated by Django 5.2.7 on 2025-10-20 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('numero_control', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('carrera', models.CharField(blank=True, max_length=200, null=True)),
                ('semestre', models.SmallIntegerField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estudiante',
            },
        ),
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('beca_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_beca', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_solicitud', models.DateField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('estatus', models.CharField(default='pendiente', max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('notas_internas', models.TextField(blank=True, null=True)),
                ('numero_control', models.ForeignKey(blank=True, db_column='numero_control', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='becas', to='api.estudiante')),
            ],
            options={
                'db_table': 'beca',
            },
        ),
    ]
