# Generated by Django 5.2.7 on 2025-10-24 01:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beca',
            name='fecha_fin',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.CreateModel(
            name='AsistenciaBeca',
            fields=[
                ('asistencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('beca_id', models.ForeignKey(blank=True, db_column='beca_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='api.beca')),
            ],
            options={
                'db_table': 'asistencia_beca',
            },
        ),
    ]
