# Generated by Django 5.2.7 on 2025-11-04 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_beca_fecha_fin_asistenciabeca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistenciabeca',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='beca',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'managed': False},
        ),
    ]
