# Generated by Django 5.2.7 on 2025-10-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorOficios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo', models.CharField(max_length=10, unique=True, verbose_name='Prefijo (S, I, J, etc.)')),
                ('contador', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Contador de Oficio',
                'verbose_name_plural': 'Contadores de Oficios',
            },
        ),
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_oficio_completo', models.CharField(editable=False, max_length=100, unique=True)),
                ('tipo_oficio', models.CharField(choices=[('S', 'Solicitud'), ('I', 'Invitación'), ('J', 'Justificante')], max_length=1, verbose_name='Tipo de Oficio')),
                ('asunto', models.CharField(max_length=255, verbose_name='Asunto')),
                ('destinatario', models.CharField(max_length=200, verbose_name='Destinatario')),
                ('cuerpo_texto', models.TextField(verbose_name='Cuerpo del Oficio')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('documento_pdf', models.FileField(blank=True, null=True, upload_to='oficios/pdf/', verbose_name='Documento PDF')),
            ],
            options={
                'verbose_name': 'Oficio',
                'verbose_name_plural': 'Oficios',
            },
        ),
    ]
